- name: all
  hosts: all
  serial: 1
  gather_facts: false
  vars:
    node_version: 6
  tasks:
    - name: stop docker
      shell:  systemctl stop docker.socket
      register: out
    - debug: var=out.stdout_lines
    
    - name: stop Kubernetes
      shell:  Systemctl stop kubelet
      register: out
    - debug: var=out.stdout_lines
    
    - name: update patches
      shell:  yum -y update --security
      register: out
    - debug: var=out.stdout_lines
    
    - name: start docker
      shell:  systemctl start docker.socket
      register: out
    - debug: var=out.stdout_lines
    
    - name: start Kubernetes
      shell:  Systemctl start kubelet
      register: out
    - debug: var=out.stdout_lines
    
    - name: verify container
      shell: docker ps
      register: out
    - debug: var=out.stdout_lines 
    
    - name: Reboot the server
      become: yes
      become_user: root
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
    - name: Wait for the reboot and reconnect 
      wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      search_regex: OpenSSH
      delay: 10
      timeout: 60
      connection: local
    
    
